---
name: 'PR Labeled Approved'

on:
  pull_request_review:
    types: [submitted]
  pull_request:

permissions:
  contents: read
  pull-requests: read


jobs:
  check_approvals:
    if: github.event_name == 'pull_request_target' || github.event_name == 'pull_request_review'
    runs-on: self-hosted-nutanix-medium
    outputs:
      result: ${{ steps.check_approvals.outputs.status }}
    steps:
      - name: Check integration test allowance status
        id: check_approvals
        uses: nutanix-cloud-native/action-check-approvals@main
        with:
          approval_labels: integration_test
